// frontend-angular/src/app/pages/profile/profile.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { DataService } from '../../services/data.service';
import { QrComponent } from '../../components/qr/qr.component';

@Component({
  selector: 'app-profile',
  template: `
    @if (api.currentUser(); as user) {
      <div class="profile-card">
        <div class="profile-header">
          <div class="profile-avatar">🧙</div>
          <div class="profile-name">
            <div class="profile-fullname">{{ user.first_name }} {{ user.last_name }}</div>
            <div class="profile-role">{{ user.role }} · {{ user.status }}</div>
          </div>
        </div>
        <div class="profile-qr">
          <div class="qr-label">QR-код участника</div>
          <app-qr [value]="user.id" [size]="120"></app-qr>
          <div class="qr-id">{{ user.id }}</div>
        </div>
        <div class="profile-details">
          <div class="detail-row">
            <span class="detail-label">ID</span>
            <span class="detail-value">{{ user.id }}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">Телефон</span>
            <span class="detail-value">{{ user.phone }}</span>
          </div>
          <div class="detail-row">
            <span class="detail-label">Статус</span>
            <span class="detail-value">{{ user.status }}</span>
          </div>
        </div>

        @if (editMode) {
          <div class="edit-section">
            <div class="edit-title">✏️ Редактировать профиль</div>
            <form [formGroup]="editForm" (ngSubmit)="saveProfile()">
              <div class="form-row">
                <input formControlName="firstName" placeholder="Имя">
                <input formControlName="lastName" placeholder="Фамилия">
              </div>
              <input formControlName="phone" placeholder="Телефон">
              <div class="row">
                <button class="btn btn-secondary btn-sm" type="submit">Сохранить</button>
                <button class="btn btn-outline btn-sm" type="button" (click)="editMode = false">Отмена</button>
              </div>
            </form>
          </div>
        }

        <div class="profile-actions">
          <button class="btn btn-outline" (click)="toggleEdit()">✏️ Редактировать</button>
          <button class="btn btn-danger" (click)="logout()">🚪 Выйти</button>
        </div>
      </div>

      @if (user.role === 'admin') {
        <div class="card">
          <div class="card-title">👥 Пользователи <span class="counter">{{ users().length }}</span></div>
          <button class="btn btn-outline btn-sm mb-2" (click)="loadUsers()">🔄 Обновить</button>
          @if (usersLoading()) {
            <div class="skeleton"></div>
          } @else {
            @for (u of users(); track u.id) {
              <div class="item">
                <div class="item-left">
                  <div class="title">{{ u.first_name }} {{ u.last_name }}</div>
                  <div class="sub">{{ u.role }} · {{ u.phone }}</div>
                </div>
                <div class="item-right">
                  <span class="badge" [class.badge-active]="u.status==='active'" [class.badge-completed]="u.status!=='active'">{{ u.status }}</span>
                  <span class="tag">{{ u.id }}</span>
                </div>
              </div>
            }
          }
        </div>
      }
    } @else {
      <div class="login-card">
        <div class="login-header">
          <div class="login-logo">⚔</div>
          <h2>Вход в Kayran</h2>
          <p class="login-sub">Платформа водных активностей</p>
        </div>
        <form [formGroup]="loginForm" (ngSubmit)="register()">
          <input formControlName="phone" type="text" placeholder="Телефон" autocomplete="tel">
          <div class="form-row">
            <input formControlName="firstName" type="text" placeholder="Имя" autocomplete="given-name">
            <input formControlName="lastName" type="text" placeholder="Фамилия" autocomplete="family-name">
          </div>
          <button class="btn btn-primary btn-block" type="submit" [disabled]="loginForm.invalid">Войти</button>
        </form>
        <div class="login-hint">Демо: +79990001122 / Анна Спортсменова</div>
      </div>
    }
  `,
  imports: [ReactiveFormsModule, QrComponent],
})
export class ProfileComponent implements OnInit {
  api = inject(ApiService);
  private auth = inject(AuthService);
  private data = inject(DataService);

  editMode = false;
  users = signal<any[]>([]);
  usersLoading = signal(false);

  editForm = new FormGroup({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    phone: new FormControl('', [Validators.required, Validators.minLength(5)]),
  });

  loginForm = new FormGroup({
    phone: new FormControl('+79990001122', [Validators.required, Validators.minLength(5)]),
    firstName: new FormControl('Анна', Validators.required),
    lastName: new FormControl('Спортсменова', Validators.required),
  });

  ngOnInit() {
    if (localStorage.getItem('kayran_token')) {
      this.auth.getMe().catch(() => {});
    }
  }

  toggleEdit() {
    const u = this.api.currentUser();
    if (!u) return;
    this.editForm.patchValue({ firstName: u.first_name, lastName: u.last_name, phone: u.phone });
    this.editMode = !this.editMode;
  }

  async saveProfile() {
    if (this.editForm.invalid) return;
    try {
      await this.auth.updateProfile({
        first_name: this.editForm.value.firstName!,
        last_name: this.editForm.value.lastName!,
        phone: this.editForm.value.phone!,
      });
      this.editMode = false;
    } catch (e: any) { alert(e.message); }
  }

  async register() {
    if (this.loginForm.invalid) return;
    const { phone, firstName, lastName } = this.loginForm.value;
    try {
      await this.auth.login(phone!);
    } catch {
      try {
        await this.auth.register(firstName!, lastName!, phone!);
      } catch (e: any) { alert(e.message); return; }
    }
    this.loadUsers();
  }

  async loadUsers() {
    this.usersLoading.set(true);
    try { this.users.set(await this.data.getUsers()); }
    catch { this.users.set([]); }
    this.usersLoading.set(false);
  }

  logout() { this.auth.logout(); }
}

// frontend-react/src/pages/profile/Profile.tsx
import { useState, useEffect, useCallback } from 'react'
import { useAuth, login, register, updateProfile } from '../../services/auth'
import { dataService } from '../../services/data'

export default function Profile() {
  const { user, token, setAuth, logout } = useAuth()
  const [editMode, setEditMode] = useState(false)
  const [users, setUsers] = useState<any[]>([])
  const [phone, setPhone] = useState('+79990001122')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const handleRegister = async () => {
    setLoading(true); setError('')
    try {
      const res = await login(phone).catch(() => null)
      if (res) { setAuth(res); return }
      const r = await register(firstName || 'User', lastName, phone)
      setAuth(r)
    } catch (e: any) { setError(e.message || 'Ошибка') }
    finally { setLoading(false) }
  }

  const saveProfile = async () => {
    if (!user) return
    try { await updateProfile(user.id, { first_name: firstName || user.first_name, last_name: lastName || user.last_name }); setEditMode(false) }
    catch (e: any) { setError(e.message) }
  }

  const loadUsers = async () => { try { setUsers(await dataService.getUsers()) } catch {} }

  useEffect(() => { if (user) { setFirstName(user.first_name); setLastName(user.last_name || '') } }, [user])

  if (!token || !user) return (
    <div className="page-profile">
      <div className="card" style={{ maxWidth: 380, margin: '0 auto', padding: 20 }}>
        <h2 style={{ textAlign: 'center' }}>Вход</h2>
        <div className="form-group">
          <label>Телефон</label>
          <input className="input" value={phone} onChange={e => setPhone(e.target.value)} />
        </div>
        <div className="form-group">
          <label>Имя</label>
          <input className="input" value={firstName} onChange={e => setFirstName(e.target.value)} placeholder="Имя" />
        </div>
        <div className="form-group">
          <label>Фамилия</label>
          <input className="input" value={lastName} onChange={e => setLastName(e.target.value)} placeholder="Фамилия" />
        </div>
        {error && <div className="alert alert-error">{error}</div>}
        <button className="btn btn-primary" onClick={handleRegister} disabled={loading} style={{ width: '100%' }}>
          {loading ? 'Загрузка...' : 'Войти / Зарегистрироваться'}
        </button>
        <p className="hint" style={{ textAlign: 'center', marginTop: 10, fontSize: 12, color: 'var(--text-muted)' }}>
          Демо: +79990001122 / Анна Спортсменова
        </p>
      </div>
    </div>
  )

  return (
    <div className="page-profile">
      <div className="card profile-card">
        <div className="profile-avatar">{user.first_name[0]}{user.last_name?.[0]}</div>
        <h3>{user.first_name} {user.last_name}</h3>
        <div className="profile-role">{user.role}</div>
        <div className="profile-qr">
          <canvas id="qr-canvas" />
        </div>
        <div className="profile-detail"><span>ID:</span> {user.id}</div>
        <div className="profile-detail"><span>Телефон:</span> {user.phone}</div>
        <div className="profile-detail"><span>Статус:</span> {user.status || 'active'}</div>
      </div>

      {editMode ? (
        <div className="card" style={{ padding: 16, marginTop: 8 }}>
          <div className="form-group">
            <label>Имя</label>
            <input className="input" value={firstName} onChange={e => setFirstName(e.target.value)} />
          </div>
          <div className="form-group">
            <label>Фамилия</label>
            <input className="input" value={lastName} onChange={e => setLastName(e.target.value)} />
          </div>
          {error && <div className="alert alert-error">{error}</div>}
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-primary" onClick={saveProfile}>Сохранить</button>
            <button className="btn btn-ghost" onClick={() => setEditMode(false)}>Отмена</button>
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
          <button className="btn btn-primary" onClick={() => setEditMode(true)}>Редактировать</button>
          <button className="btn btn-ghost" onClick={logout}>Выйти</button>
        </div>
      )}

      {user?.role === 'system_admin' && (
        <div style={{ marginTop: 16 }}>
          <button className="btn btn-secondary" onClick={loadUsers}>Загрузить пользователей</button>
          {users.length > 0 && (
            <div className="card" style={{ marginTop: 8, padding: 8 }}>
              {users.map((u: any) => (
                <div key={u.id} className="profile-detail">{u.first_name} {u.last_name} — {u.role}</div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
