// frontend-react/src/pages/rentals/Rentals.tsx
import { useEffect, useState } from 'react'
import { eventsService } from '../../services/events'
import { rentalsService } from '../../services/rentals'

export default function Rentals() {
  const [rentals, setRentals] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [showOnlyActive, setShowOnlyActive] = useState(false)

  const loadRentals = async () => {
    setLoading(true)
    try {
      const events = await eventsService.getAll('rental')
      const enriched = await Promise.all(
        events.map(async (e: any) => {
          let participants: any[] = []
          try { participants = await eventsService.getParticipants(e.id) } catch {}
          return { ...e, participants }
        })
      )
      setRentals(enriched)
    } catch {}
    setLoading(false)
  }

  useEffect(() => { loadRentals() }, [])

  const returnRental = async (r: any) => {
    try { await rentalsService.returnRental(r.id); loadRentals() }
    catch (e: any) { alert(e.message) }
  }

  const reportDamage = async (r: any) => {
    const level = prompt('Уровень повреждения (1-5):', '1')
    if (!level) return
    const notes = prompt('Примечания:') || ''
    try { await rentalsService.reportDamage(r.id, Number(level), notes); loadRentals() }
    catch (e: any) { alert(e.message) }
  }

  const filtered = showOnlyActive ? rentals.filter((r: any) => r.status === 'active' || r.status === 'draft') : rentals

  return (
    <div className="page-rentals">
      <div className="toolbar">
        <button className="btn btn-ghost btn-sm" onClick={loadRentals}>{'\uD83D\uDD04'}</button>
        <label className="tgl">
          <input type="checkbox" checked={showOnlyActive} onChange={e => setShowOnlyActive(e.target.checked)} />
          <span className="tgl-slider" />
        </label>
        <span className="toolbar-count">{filtered.length}</span>
      </div>

      {loading && [1,2,3].map(i => <div key={i} className="card skeleton" style={{ height: 60 }} />)}
      {!loading && filtered.map((r: any) => (
        <div key={r.id} className="card rental-card">
          <div className="rental-info">
            <div className="rental-title">{r.title || `Аренда #${r.id}`}</div>
            <div className="rental-status"><span className={`badge badge-${r.status}`}>{r.status}</span></div>
            {r.start_time && <div className="rental-date">{new Date(r.start_time).toLocaleDateString()} — {r.end_time ? new Date(r.end_time).toLocaleDateString() : 'текущая'}</div>}
            <div className="rental-id">ID: {r.id}</div>
            {r.event && <div className="rental-id">Лодка: {r.boat_id || '—'}</div>}
          </div>
          {r.status === 'active' && (
            <div className="rental-actions" style={{ display: 'flex', gap: 4 }}>
              <button className="btn btn-primary btn-xs" onClick={() => returnRental(r)}>Вернуть</button>
              <button className="btn btn-ghost btn-xs" onClick={() => reportDamage(r)}>{'\u26A0'} Повреждение</button>
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

// frontend-angular/src/app/pages/rentals/rentals.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { ApiService } from '../../services/api.service';
import type { Rental, Boat, Event } from '../../models/models';

@Component({
  selector: 'app-rentals',
  template: `
    <div class="card">
      <div class="row">
        <button class="btn btn-primary" (click)="loadRentals()">🔄</button>
        <button class="btn btn-outline" (click)="showOnlyActive.set(!showOnlyActive()); loadRentals()">
          {{ showOnlyActive() ? 'Все' : 'Активные' }}
        </button>
        <span class="toolbar-count">{{ rentals().length }}</span>
      </div>
    </div>

    @if (loading()) {
      <div class="skeleton"></div><div class="skeleton"></div>
    } @else if (rentals().length === 0) {
      <div class="empty"><div class="icon">📋</div><p>Нет аренд</p></div>
    } @else {
      @for (r of rentals(); track r.id) {
        <div class="rental-card" [class.active]="r.status==='active'" [class.completed]="r.status==='completed'">
          <div class="rental-header">
            <div class="rental-title">{{ getBoatTitle(r) }}</div>
            <span class="badge" [class.badge-rented]="r.status==='active'" [class.badge-completed]="r.status==='completed'">{{ r.status }}</span>
          </div>
          <div class="rental-meta">
            {{ formatDate(r.start_time) }}
            @if (r.end_time) {
              <span> — {{ formatDate(r.end_time) }}</span>
            }
          </div>
          <div class="rental-meta">ID: {{ r.id }} · Лодка: {{ r.boat_id }}</div>
          @if (r.status === 'active') {
            <div class="rental-actions">
              <button class="btn btn-sm btn-success" (click)="returnRental(r)">✅ Вернуть</button>
              <button class="btn btn-sm btn-danger" (click)="reportDamage(r)">⚠ Повреждение</button>
            </div>
          }
        </div>
      }
    }
  `,
  standalone: true,
})
export class RentalsComponent implements OnInit {
  private api = inject(ApiService);

  rentals = signal<any[]>([]);
  loading = signal(true);
  showOnlyActive = signal(false);

  ngOnInit() { this.loadRentals(); }

  formatDate(d: string) {
    return new Date(d).toLocaleDateString() + ' ' + new Date(d).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  getBoatTitle(r: any): string {
    if (r.boat && r.boat.title) return r.boat.title;
    if (r.boat && r.boat.serial_number) return r.boat.serial_number;
    return r.boat_id;
  }

  async loadRentals() {
    this.loading.set(true);
    try {
      const all: any[] = await this.api.get<any[]>('/events?event_type=rental');
      const enriched: any[] = [];
      for (const ev of all) {
        try {
          const participants = await this.api.get<any[]>('/events/' + ev.id + '/participants');
          for (const p of participants) {
            enriched.push({ ...p, event: ev, event_id: ev.id, boat_id: p.id, start_time: ev.start_time, end_time: ev.end_time, status: ev.status });
          }
        } catch {}
      }
      this.rentals.set(
        this.showOnlyActive()
          ? enriched.filter(r => r.status === 'active')
          : enriched
      );
    } catch (e: any) {
      this.rentals.set([]);
    }
    this.loading.set(false);
  }

  async returnRental(r: any) {
    try {
      await this.api.put<any>('/rentals/' + r.event_id + '/return', {});
      this.loadRentals();
    } catch (e: any) { alert(e.message); }
  }

  private conditionLabel(score: string): string {
    const map: Record<string, string> = { '1': 'damaged', '2': 'poor', '3': 'fair', '4': 'good', '5': 'excellent' };
    return map[score] || 'fair';
  }

  async reportDamage(r: any) {
    const level = prompt('Уровень повреждения (1-5):', '3');
    if (!level) return;
    const notes = prompt('Примечания:', '') || '';
    try {
      await this.api.put<any>('/rentals/' + r.event_id + '/damage', {
        condition_level: this.conditionLabel(level),
        notes,
      });
      this.loadRentals();
    } catch (e: any) { alert(e.message); }
  }
}
