// frontend-react/src/pages/sport/Sport.tsx
import { useEffect, useState } from 'react'
import { sportService } from '../../services/sport'

const formatLabels: Record<string, string> = {
  single_elimination: 'Олимпийская система',
  round_robin: 'Круговая',
  time_trial: 'На время',
}

export default function Sport() {
  const [teams, setTeams] = useState<any[]>([])
  const [tournaments, setTournaments] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  const [showTeamForm, setShowTeamForm] = useState(false)
  const [editingTeamId, setEditingTeamId] = useState<number | null>(null)
  const [teamTitle, setTeamTitle] = useState('')

  const [showTournamentForm, setShowTournamentForm] = useState(false)
  const [editingTournamentId, setEditingTournamentId] = useState<number | null>(null)
  const [tournamentTitle, setTournamentTitle] = useState('')
  const [tournamentFormat, setTournamentFormat] = useState('single_elimination')

  const [selectedTournamentId, setSelectedTournamentId] = useState<number | null>(null)
  const [tournamentMatches, setTournamentMatches] = useState<any[]>([])
  const [matchesLoading, setMatchesLoading] = useState(false)
  const [allMatches, setAllMatches] = useState<Record<string, any[]>>({})

  const loadData = async () => {
    setLoading(true)
    try { const [tms, trns] = await Promise.all([sportService.getTeams(), sportService.getTournaments()]); setTeams(tms); setTournaments(trns) }
    catch {}
    setLoading(false)
  }

  useEffect(() => { loadData() }, [])

  const saveTeam = async () => {
    try {
      if (editingTeamId) await sportService.updateTeam(editingTeamId, { title: teamTitle })
      else await sportService.createTeam({ title: teamTitle })
      setShowTeamForm(false); setEditingTeamId(null); setTeamTitle(''); loadData()
    } catch (e: any) { alert(e.message) }
  }

  const deleteTeam = async (id: number) => {
    if (!confirm('Удалить команду?')) return
    try { await sportService.deleteTeam(id); loadData() } catch {}
  }

  const saveTournament = async () => {
    try {
      if (editingTournamentId) await sportService.updateTournament(editingTournamentId, { title: tournamentTitle, format: tournamentFormat })
      else await sportService.createTournament({ title: tournamentTitle, format: tournamentFormat })
      setShowTournamentForm(false); setEditingTournamentId(null); setTournamentTitle(''); setTournamentFormat('single_elimination'); loadData()
    } catch (e: any) { alert(e.message) }
  }

  const deleteTournament = async (id: number) => {
    if (!confirm('Удалить турнир?')) return
    try { await sportService.deleteTournament(id); loadData() } catch {}
  }

  const selectTournament = async (t: any) => {
    if (selectedTournamentId === t.id) { setSelectedTournamentId(null); return }
    setSelectedTournamentId(t.id)
    if (allMatches[t.id]) { setTournamentMatches(allMatches[t.id]); return }
    setMatchesLoading(true)
    try {
      const matches = await sportService.getMatches(t.id)
      setAllMatches(prev => ({ ...prev, [t.id]: matches }))
      setTournamentMatches(matches)
    } catch {}
    setMatchesLoading(false)
  }

  const matchesCount = (tournamentId: number) => allMatches[tournamentId]?.length ?? 0

  return (
    <div className="page-sport">
      <div className="toolbar">
        <button className="btn btn-ghost btn-sm" onClick={loadData}>{'\uD83D\uDD04'}</button>
        <button className="btn btn-primary btn-sm" onClick={() => { setShowTeamForm(true); setEditingTeamId(null); setTeamTitle('') }}>+ Команда</button>
        <button className="btn btn-primary btn-sm" onClick={() => { setShowTournamentForm(true); setEditingTournamentId(null); setTournamentTitle(''); setTournamentFormat('single_elimination') }}>+ Турнир</button>
      </div>

      {showTeamForm && (
        <div className="card" style={{ padding: 12, marginBottom: 8 }}>
          <div className="form-group"><input className="input" value={teamTitle} onChange={e => setTeamTitle(e.target.value)} placeholder="Название команды" /></div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-primary btn-sm" onClick={saveTeam}>Сохранить</button>
            <button className="btn btn-ghost btn-sm" onClick={() => { setShowTeamForm(false); setEditingTeamId(null) }}>Отмена</button>
          </div>
        </div>
      )}

      {showTournamentForm && (
        <div className="card" style={{ padding: 12, marginBottom: 8 }}>
          <div className="form-group"><input className="input" value={tournamentTitle} onChange={e => setTournamentTitle(e.target.value)} placeholder="Название турнира" /></div>
          <div className="form-group">
            <select className="input" value={tournamentFormat} onChange={e => setTournamentFormat(e.target.value)}>
              {Object.entries(formatLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
            </select>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-primary btn-sm" onClick={saveTournament}>Сохранить</button>
            <button className="btn btn-ghost btn-sm" onClick={() => { setShowTournamentForm(false); setEditingTournamentId(null) }}>Отмена</button>
          </div>
        </div>
      )}

      <h3 style={{ marginTop: 8 }}>Команды ({teams.length})</h3>
      {teams.map(t => (
        <div key={t.id} className="card team-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span>{t.title}</span>
          <div style={{ display: 'flex', gap: 4 }}>
            <button className="btn btn-ghost btn-xs" onClick={() => { setEditingTeamId(t.id); setTeamTitle(t.title); setShowTeamForm(true) }}>{'\u270F'}</button>
            <button className="btn btn-ghost btn-xs" onClick={() => deleteTeam(t.id)}>{'\uD83D\uDDD1'}</button>
          </div>
        </div>
      ))}

      <h3 style={{ marginTop: 12 }}>Турниры ({tournaments.length})</h3>
      {tournaments.map(t => (
        <div key={t.id} className="card tournament-card" onClick={() => selectTournament(t)} style={{ cursor: 'pointer' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <div className="tournament-title">{t.title}</div>
              <div className="tournament-meta">{formatLabels[t.format] || t.format} • {matchesCount(t.id)} матч(ей)</div>
            </div>
            <div style={{ display: 'flex', gap: 4 }}>
              <button className="btn btn-ghost btn-xs" onClick={e => { e.stopPropagation(); setEditingTournamentId(t.id); setTournamentTitle(t.title); setTournamentFormat(t.format); setShowTournamentForm(true) }}>{'\u270F'}</button>
              <button className="btn btn-ghost btn-xs" onClick={e => { e.stopPropagation(); deleteTournament(t.id) }}>{'\uD83D\uDDD1'}</button>
            </div>
          </div>
          {selectedTournamentId === t.id && (
            <div className="tournament-brackets" style={{ marginTop: 8 }}>
              {matchesLoading ? <div className="skeleton" style={{ height: 40 }} /> : (
                tournamentMatches.length === 0
                  ? <div style={{ color: 'var(--text-muted)', fontStyle: 'italic', textAlign: 'center' }}>Нет матчей</div>
                  : tournamentMatches.map((m: any) => (
                      <div key={m.id} className="match-card">
                        <div className="match-teams">
                          <span className="match-team">{m.team_a_id}</span>
                          <span className="match-score">{m.score_a} : {m.score_b}</span>
                          <span className="match-team">{m.team_b_id}</span>
                        </div>
                        <div className="match-status">{m.status}</div>
                      </div>
                    ))
              )}
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

// frontend-angular/src/app/pages/sport/sport.component.ts
import { Component, OnInit, signal, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { SportService } from '../../services/sport.service';
import type { Team, Tournament, Match } from '../../models/models';

@Component({
  selector: 'app-sport',
  template: `
    <div class="card">
      <div class="row">
        <button class="btn btn-primary" (click)="loadTeams(); loadTournaments()">🔄</button>
        <button class="btn btn-secondary" (click)="showTeamForm.set(!showTeamForm()); showTournamentForm.set(false)">+ Команда</button>
        <button class="btn btn-outline" (click)="showTournamentForm.set(!showTournamentForm()); showTeamForm.set(false)">+ Турнир</button>
      </div>
    </div>

    @if (showTeamForm()) {
      <div class="card">
        <div class="card-title">{{ editingTeamId() ? '✏️ Редактировать команду' : '➕ Новая команда' }}</div>
        <form [formGroup]="teamForm" (ngSubmit)="saveTeam()">
          <input formControlName="title" placeholder="Название команды">
          <div class="row">
            <button class="btn btn-secondary" type="submit">{{ editingTeamId() ? 'Сохранить' : 'Создать' }}</button>
            <button class="btn btn-outline" type="button" (click)="cancelTeamForm()">Отмена</button>
          </div>
        </form>
      </div>
    }

    @if (showTournamentForm()) {
      <div class="card">
        <div class="card-title">{{ editingTournamentId() ? '✏️ Редактировать турнир' : '➕ Новый турнир' }}</div>
        <form [formGroup]="tournamentForm" (ngSubmit)="saveTournament()">
          <input formControlName="title" placeholder="Название турнира">
          <select formControlName="format">
            <option value="single_elimination">Single Elimination</option>
            <option value="round_robin">Round Robin</option>
            <option value="time_trial">Time Trial</option>
          </select>
          <div class="row">
            <button class="btn btn-secondary" type="submit">{{ editingTournamentId() ? 'Сохранить' : 'Создать' }}</button>
            <button class="btn btn-outline" type="button" (click)="cancelTournamentForm()">Отмена</button>
          </div>
        </form>
      </div>
    }

    <div class="card">
      <div class="card-title">Команды <span class="counter">{{ teams().length }}</span></div>
      @if (teamsLoading()) {
        <div class="skeleton"></div>
      } @else if (teams().length === 0) {
        <div class="empty"><div class="icon">👥</div><p>Нет команд</p></div>
      } @else {
        @for (t of teams(); track t.id) {
          <div class="item">
            <div class="item-left">
              <div class="title">{{ t.title }}</div>
              <div class="sub">{{ t.status }} · Капитан: {{ t.captain_user_id }}</div>
            </div>
            <div class="item-right">
              <div class="actions">
                <button class="btn btn-xs btn-outline" (click)="editTeam(t)">✏️</button>
                <button class="btn btn-xs btn-danger" (click)="deleteTeam(t)">🗑</button>
              </div>
            </div>
          </div>
        }
      }
    </div>

    <div class="card">
      <div class="card-title">Турниры <span class="counter">{{ tournaments().length }}</span></div>
      @if (tournamentsLoading()) {
        <div class="skeleton"></div>
      } @else if (tournaments().length === 0) {
        <div class="empty"><div class="icon">🏆</div><p>Нет турниров</p></div>
      } @else {
        @for (t of tournaments(); track t.id) {
          <div class="item" (click)="selectTournament(t)" style="cursor:pointer;">
            <div class="item-left">
              <div class="title">{{ t.title }}</div>
              <div class="sub">{{ formatLabel(t.format) }} · {{ t.status }}</div>
            </div>
            <div class="item-right">
              <span class="tag" style="margin-right:4px;">{{ matchesCount(t.id) }} матчей</span>
              <div class="actions">
                <button class="btn btn-xs btn-outline" (click)="$event.stopPropagation(); editTournament(t)">✏️</button>
                <button class="btn btn-xs btn-danger" (click)="$event.stopPropagation(); deleteTournament(t)">🗑</button>
              </div>
            </div>
          </div>
          @if (selectedTournamentId() === t.id) {
            <div style="padding:4px 0 0 8px;border-left:1px solid rgba(220,38,38,0.06);margin-bottom:4px;">
              @if (matchesLoading()) {
                <div class="skeleton" style="height:20px"></div>
              } @else if (tournamentMatches().length === 0) {
                <div style="font-size:9px;color:var(--text-muted);font-style:italic;padding:4px 0;">Нет матчей</div>
              } @else {
                <div class="bracket-round">
                  <div class="bracket-round-title">🗓 Матчи турнира</div>
                      @for (m of tournamentMatches(); track m.id) {
                    <div class="match-card">
                      <div class="match-teams">
                        <span>{{ m.team_a_id || '—' }}</span>
                        <span class="match-vs">vs</span>
                        <span>{{ m.team_b_id || '—' }}</span>
                      </div>
                      <div class="match-score">
                        {{ m.score_a }}{{ ':' }}{{ m.score_b }}
                      </div>
                    </div>
                  }
                </div>
              }
            </div>
          }
        }
      }
    </div>
  `,
  imports: [ReactiveFormsModule],
})
export class SportComponent implements OnInit {
  private sport = inject(SportService);

  teams = signal<Team[]>([]);
  tournaments = signal<Tournament[]>([]);
  teamsLoading = signal(true);
  tournamentsLoading = signal(true);

  showTeamForm = signal(false);
  editingTeamId = signal<string | null>(null);
  showTournamentForm = signal(false);
  editingTournamentId = signal<string | null>(null);

  selectedTournamentId = signal<string | null>(null);
  tournamentMatches = signal<Match[]>([]);
  matchesLoading = signal(false);
  private allMatches: Record<string, Match[]> = {};

  teamForm = new FormGroup({
    title: new FormControl('', Validators.required),
  });

  tournamentForm = new FormGroup({
    title: new FormControl('', Validators.required),
    format: new FormControl('single_elimination', Validators.required),
  });

  ngOnInit() { this.loadTeams(); this.loadTournaments(); }

  formatLabel(f: string): string {
    const map: Record<string, string> = { single_elimination: '1v1', round_robin: 'Round Robin', time_trial: 'Time Trial' };
    return map[f] || f;
  }

  matchesCount(tournamentId: string): number {
    return (this.allMatches[tournamentId] || []).length;
  }

  async selectTournament(t: Tournament) {
    if (this.selectedTournamentId() === t.id) {
      this.selectedTournamentId.set(null);
      return;
    }
    this.selectedTournamentId.set(t.id);
    if (!this.allMatches[t.id]) {
      this.matchesLoading.set(true);
      try {
        const matches = await this.sport.getMatches(t.id);
        this.allMatches[t.id] = matches;
        this.tournamentMatches.set(matches);
      } catch {
        this.allMatches[t.id] = [];
        this.tournamentMatches.set([]);
      }
      this.matchesLoading.set(false);
    } else {
      this.tournamentMatches.set(this.allMatches[t.id]);
    }
  }

  async loadTeams() {
    this.teamsLoading.set(true);
    try { this.teams.set(await this.sport.getTeams()); }
    catch { this.teams.set([]); }
    finally { this.teamsLoading.set(false); }
  }

  async loadTournaments() {
    this.tournamentsLoading.set(true);
    try { this.tournaments.set(await this.sport.getTournaments()); }
    catch { this.tournaments.set([]); }
    finally { this.tournamentsLoading.set(false); }
  }

  editTeam(t: Team) {
    this.editingTeamId.set(t.id);
    this.teamForm.patchValue({ title: t.title });
    this.showTeamForm.set(true);
  }

  cancelTeamForm() {
    this.showTeamForm.set(false);
    this.editingTeamId.set(null);
    this.teamForm.reset({ title: '' });
  }

  async saveTeam() {
    if (this.teamForm.invalid) return;
    try {
      if (this.editingTeamId()) {
        await this.sport.updateTeam(this.editingTeamId()!, { title: this.teamForm.value.title! });
      } else {
        await this.sport.createTeam({ title: this.teamForm.value.title! } as Team);
      }
      this.cancelTeamForm();
      this.loadTeams();
    } catch (e: any) { alert(e.message); }
  }

  async deleteTeam(t: Team) {
    if (!confirm('Удалить команду "' + t.title + '"?')) return;
    try { await this.sport.deleteTeam(t.id); this.loadTeams(); }
    catch (e: any) { alert(e.message); }
  }

  editTournament(t: Tournament) {
    this.editingTournamentId.set(t.id);
    this.tournamentForm.patchValue({ title: t.title, format: t.format });
    this.showTournamentForm.set(true);
  }

  cancelTournamentForm() {
    this.showTournamentForm.set(false);
    this.editingTournamentId.set(null);
    this.tournamentForm.reset({ title: '', format: 'single_elimination' });
  }

  async saveTournament() {
    if (this.tournamentForm.invalid) return;
    try {
      if (this.editingTournamentId()) {
        await this.sport.updateTournament(this.editingTournamentId()!, {
          title: this.tournamentForm.value.title!,
          format: this.tournamentForm.value.format!,
        });
      } else {
        await this.sport.createTournament({
          title: this.tournamentForm.value.title!,
          format: this.tournamentForm.value.format!,
        } as Tournament);
      }
      this.cancelTournamentForm();
      this.loadTournaments();
    } catch (e: any) { alert(e.message); }
  }

  async deleteTournament(t: Tournament) {
    if (!confirm('Удалить турнир "' + t.title + '"?')) return;
    try { await this.sport.deleteTournament(t.id); this.loadTournaments(); }
    catch (e: any) { alert(e.message); }
  }
}
