// frontend-angular/src/app/pages/tariffs/tariffs.component.ts
import { Component, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-tariffs',
  template: `
    <div class="card">
      <div class="card-title">💰 Тарифы</div>
      <p style="font-size:10px;color:var(--text3);font-style:italic;margin-bottom:6px;">
        Выгодные предложения для каждого
      </p>
    </div>

    @for (t of tariffs; track t.id) {
      <div class="route-card" style="position:relative;overflow:hidden;">
        @if (t.badge) {
          <div style="position:absolute;top:4px;right:-20px;background:var(--red);color:#fff;padding:1px 24px;font-size:6px;font-family:var(--font-display);text-transform:uppercase;letter-spacing:0.5px;transform:rotate(45deg);">
            {{ t.badge }}
          </div>
        }
        <div style="display:flex;justify-content:space-between;align-items:start;">
          <div>
            <div class="route-title">{{ t.name }}</div>
            <div class="route-meta">{{ t.desc }}</div>
          </div>
          <div style="text-align:right;">
            <div style="font-family:var(--font-display);font-size:22px;font-weight:700;color:var(--red-light);line-height:1;">
              {{ t.price === 0 ? '0' : t.price }}
            </div>
            <div style="font-size:7px;color:var(--text3);text-transform:uppercase;letter-spacing:0.5px;">
              {{ t.price === 0 ? 'Бесплатно' : '₽ / час' }}
            </div>
          </div>
        </div>
        <div style="margin-top:6px;display:flex;flex-wrap:wrap;gap:2px;">
          @for (f of t.features; track f) {
            <span class="tag tag-green">✓ {{ f }}</span>
          }
        </div>
        <a routerLink="/boats" class="btn btn-sm btn-primary" style="margin-top:6px;width:100%;">
          {{ t.price === 0 ? 'Забронировать бесплатно' : 'Выбрать тариф' }}
        </a>
      </div>
    }
  `,
  imports: [RouterLink],
  standalone: true,
})
export class TariffsComponent {
  tariffs = [
    {
      id: 'standard', name: 'Стандартный', desc: 'Базовый тариф для всех',
      price: 1500, badge: '',
      features: ['Лодка в аренду', 'Спасательный жилет', 'Весла', '1 час']
    },
    {
      id: 'family', name: 'Семейный', desc: 'Для двоих и более — выгодно',
      price: 1200, badge: '-20%',
      features: ['Лодка до 4 мест', 'Скидка 20%', 'Приоритетная посадка', 'Доп. оборудование']
    },
    {
      id: 'student', name: 'Студенческий', desc: 'При предъявлении студенческого билета',
      price: 900, badge: '-40%',
      features: ['Любая лодка', 'Скидка 40%', 'Снаряжение включено']
    },
    {
      id: 'inclusive', name: 'Инклюзивный', desc: 'Для людей с ограниченными возможностями здоровья',
      price: 0, badge: 'Бесплатно',
      features: ['Бесплатно', 'Специальные лодки', 'Помощник', 'Доступная среда']
    },
  ];
}

// frontend-react/src/pages/tariffs/Tariffs.tsx
import { useNavigate } from 'react-router-dom'

const tariffs = [
  { id: 'Standard', label: 'Стандарт', price: 1500, desc: 'Базовый тариф проката. Включено: лодка, спасательный жилет, весла.', features: ['Лодка', 'Спасательный жилет', 'Весла', 'Инструктаж'], badge: '' },
  { id: 'Family', label: 'Семейный', price: 1200, desc: 'Для двоих. Скидка 20% при аренде двух мест.', features: ['Всё из Стандарта', 'Двухместная лодка', 'Скидка 20%'], badge: '-20%' },
  { id: 'Student', label: 'Студенческий', price: 900, desc: 'Для учащихся при предъявлении студенческого билета.', features: ['Всё из Стандарта', 'Скидка 40%'], badge: '-40%' },
  { id: 'Inclusive', label: 'Инклюзив', price: 0, desc: 'Для людей с ограниченными возможностями здоровья. Бесплатно.', features: ['Всё из Стандарта', 'Адаптивное оборудование', 'Сопровождение'], badge: 'Бесплатно' },
]

export default function Tariffs() {
  const navigate = useNavigate()

  return (
    <div className="page-tariffs">
      <div className="card" style={{ textAlign: 'center', padding: 20, marginBottom: 8 }}>
        <h2>Тарифы</h2>
        <p style={{ color: 'var(--text-muted)' }}>Выберите подходящий тариф для аренды</p>
      </div>

      <div className="tariffs-grid">
        {tariffs.map(t => (
          <div key={t.id} className="card tariff-card">
            {t.badge && <span className="tariff-badge">{t.badge}</span>}
            <h3 className="tariff-name">{t.label}</h3>
            <div className="tariff-price">
              {t.price === 0 ? 'Бесплатно' : `${t.price} ₽`}
              {t.price > 0 && <span className="tariff-period">/ час</span>}
            </div>
            <p className="tariff-desc">{t.desc}</p>
            <div className="tariff-features">
              {t.features.map((f, i) => <span key={i} className="tariff-feature">{'\u2713'} {f}</span>)}
            </div>
            <button className="btn btn-primary" onClick={() => navigate('/boats')}>Забронировать</button>
          </div>
        ))}
      </div>
    </div>
  )
}
